baseURL: "https://shantanu-sg-01.github.io" 
title: Shantanu S. Gulawani
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research 
          url: research/
          weight: 3
        - name: For Students
          url: students/
          weight: 2
        - name: Blog
          url: https://shantanusg.substack.com
          weight: 4

params:
    description: "I am Assistant Professor of Aerospace Engineering at MVJ College of Engineering. I am interested in Design, Optimization, Computing and Coding."
    author: Shantanu S. Gulawani
    googleAnalyticsID: "G-8NPK6Q55VE"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["For Students","Research","About me","Blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: true
    math: true
    profileMode:
          enabled: true
          title: Shantanu S. Gulawani
          subtitle: |
            Welcome!
            
            
            
            I am a faculty member in the Aerospace Engineering Department at MVJ College of Engineering, Bengaluru. This website serves as a hub for my academic activities ‚Äî a place where I share my research directions, student collaboration opportunities, and thoughts on engineering education and scientific computing.
            
            
            
            My work revolves around computational frameworks, algorithm design, and performance-focused software, often drawing inspiration from functional programming and declarative paradigms.
            
            
            
            üì¨ Feel free to reach out via email for collaboration.
            
            
            
            [üìù I occasionally post blogs on Substack](https://shantanusg.substack.com).  
            
            
            
            [üìÖ Book a time to talk on Calendly](https://calendly.com/shantanu_as-mvjce/office-houre-in-person)
          imageUrl: "picture4sq.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: For Students
              url: students/
            - name: Courses
              url: courses/
            - name: Reading & Inspiration
              url: reading/
            - name: Research
              url: research/
            - name: Blog
              url: https://shantanusg.substack.com

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:shantanu_as@mvjce.edu.in
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=hsilxtIAAAAJ&hl=en
        - name: LinkedIn
          url: https://www.linkedin.com/in/shantanu-gulawani-a133b2131

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Shantanu S. Gulawani"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
